version: '2.2'

services:
  es-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es-ingest-1
    environment:
      - node.name=es-ingest-1
      - node.master: false
      - node.data: false
      - node.ingest: true
      - search.remote.connect: false
      - discovery.seed_hosts=es-master-1
      - cluster.initial_master_nodes=es-master-1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge