version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es01
    environment:
      - cluster.name=es-cluster
      - node.name=es01
      - network.host=0.0.0.0
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - LimitMEMLOCK=infinity
      - MAX_LOCKED_MEMORY=unlimited
      - xpack.monitoring.collection.enabled=true
    ports:
      - 9200:9200
    networks:
      - elastic
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 65536
        hard: 65536
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - server.host=0.0.0.0
    ports:
      - "5601:5601"
    networks:
      - elastic
volumes:
  data01:
    driver: local
networks:
  elastic:
    driver: bridge

#wsl -d docker-desktop
#sysctl -w vm.max_map_count=262144
#sysctl -w vm.swappiness=1
#sysctl -p

#docker-compose up