version: '2.2'
services:
  es-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es-master-1
    environment:
      - cluster.name=es-cluster
      - node.name=es-master-1
      - node.master=true
      - node.data=true
      - network.host=0.0.0.0
      - discovery.seed_hosts=es-master-1
      - cluster.initial_master_nodes=es-master-1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - LimitMEMLOCK=infinity
      - MAX_LOCKED_MEMORY=unlimited
      - xpack.monitoring.collection.enabled=true
    ports:
      - 9200:9200
    networks:
      - elastic
    volumes:
    - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 65536
        hard: 65536
      nofile:
        soft: 65536
        hard: 65536
  es-ingest-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es-ingest-1
    environment:
      - cluster.name=es-cluster
      - node.name=es-ingest-1      
      - node.master=false
      - node.data=false
      - node.ingest=true
      - search.remote.connect=false
      - network.host=0.0.0.0
      - discovery.seed_hosts=es-master-1
      - cluster.initial_master_nodes=es-master-1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - LimitMEMLOCK=infinity
      - MAX_LOCKED_MEMORY=unlimited
      - xpack.monitoring.collection.enabled=true
    ports:
      - 9201:9201
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc:
        soft: 65536
        hard: 65536
      nofile:
        soft: 65536
        hard: 65536
volumes:
  data01:
    driver: local
networks:
  elastic:
    driver: bridge


#wsl -d docker-desktop
#sysctl -w vm.max_map_count=262144
#sysctl -w vm.swappiness=1
#sysctl -p

#docker-compose up